### ISSUE TITLE
Question: Is it possible to write back to modbus

### ISSUE THREAD

**Issue by bcelary** [BlackZork/mqmgateway#1]
Hi Łukasz,
Sorry to ask but I am not able to figure it out based on the README. Is it possible to write to a MODBUS device from the MQTT side? I get a sense that the gateway works only one way (i.e. MODBUS --> MQTT). Maybe it is worth mentioning in the README.

Thanks!

**Comment by BlackZork** [comment]
Yes.

See:
"A commands section" - in README.

Some examples:
[command tests](https://github.com/BlackZork/mqmgateway/blob/master/unittests/mqtt_command_tests.cpp)

I see that there is no header formatting in README, fixing now.

**Comment by bcelary** [comment]
Super! Dzięki i pozdr!
