### ISSUE TITLE
Converter usage

### ISSUE THREAD

**Issue by wtrucci** [BlackZork/mqmgateway#74]
Hi, I need to read data from modbus registry ad int16 and divide data too.
Is it possible to do it? If I use converter I can convert on int16 or divide but not together.
Is there a way to do it?

Thanks
Regards
Walter

**Comment by BlackZork** [comment]
Cast to int16, divide by 5 and round to two decimal places:

`converter: expr.evaluate("int16(R0)/5", 2)`

see exprtk docs for more.

**Comment by wtrucci** [comment]
Hi,
thanks for tip!
Regards
Walter
